version: '3'
services:
  web-server:
    build: ./server
    ports:
      - "3001:3001"
    entrypoint: ['node', 'server.js']
    volumes:
      - ./server:/service
      - /service/node_modules
  web-client:
    build: ./client
    ports:
      - "80:80"
    entrypoint: ['npm', 'start']
    volumes:
      - ./client:/service
      - /service/node_modules

